// DemoKanbanClient_demo/src/app/tile/tile.component.ts
import { Component, Input } from '@angular/core';
import { IIssueDto } from 'src/dtos/project';

//ng generate component tile

@Component({
  selector: 'app-tile',
  templateUrl: './tile.component.html',
  styleUrls: ['./tile.component.css'],
})
export class TileComponent {
  @Input() issue?: IIssueDto;
}

<ng-container *ngIf="issue">
  <a class="list-group-item tile" [routerLink]="['/issue/edit/', issue.id]">
    <div class="row title">
      <div class="col-md-8">
        <em>{{ issue.title }}</em>
        <span class="isUrgent">{{ issue.isUrgent | isUrgent }}</span>
      </div>
      <div class="col-md-4 assigned-to">
        {{ issue.assignedPersonDisplayName | assignedTo }}
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <span class="desc">Descriptoin:</span>{{ issue.notes }}
      </div>
    </div>
  </a>
</ng-container>

// demo-kanban-app/src/components/Tile/Tile.tsx
import { IIssueDto } from "../../dtos/project";
import "./Tile.css";

type TilePorps = {
  issue: IIssueDto;
};

function Tile({ issue }: TilePorps) {
  const isUrgent = issue.isUrgent ? "!" : "";

  return (
    <a className="list-group-item tile" href={`/issue/edit/${issue.id}`}>
      <div className="row title">
        <div className="col-md-8">
          <em>{issue.title}</em>
          <span className="isUrgent">{isUrgent}</span>
        </div>
        <div className="col-md-4 assigned-to">
          {issue.assignedPersonDisplayName}
        </div>
      </div>
      <div className="row">
        <div className="col-md-12">
          <span className="desc">Descriptoin:</span>
          {issue.notes}
        </div>
      </div>
    </a>
  );
}

export default Tile;
